language: "php"

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script: 
- "composer require codeclimate/php-test-reporter --dev"
- "composer install"

script: 
- "phpunit --testsuite=unit --coverage-text --coverage-clover build/logs/clover.xml"

after_script:
- CODECLIMATE_REPO_TOKEN="0301d150bb56bd0f74f9daca051da3540f120393badc1dca3a3d0e263ab39da2" vendor/bin/test-reporter --stdout > codeclimate.json
- "sh -c 'if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then curl -X POST -d @codeclimate.json -H \"Content-Type: application/json\" -H \"User-Agent: Code Climate (PHP Test Reporter v0.1.1)\" https://codeclimate.com/test_reports  ; fi'"
